name: qeeps_dev

services:
  backend:
    image: node:18-buster-slim
    container_name: qeeps_api
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - mongodb
    environment:
      - DEV=1
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    volumes:
      - ./back/:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  mongodb:
    image: mongo
    container_name: mongo_dev
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express_dev
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  db-data:
